name: Build Artifacts
on:
  push:
    branches:
      - main

jobs:
  dummy-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: print current directory
        run: pwd
      
      - name: print message
        run: echo "This is a dummy GitHub Actions workflow running on $(date)"